###
POST http://localhost:9000/api/users HTTP/1.1
Content-Type: application/json

{
    "name": "Prueba",
    "age": 32,
    "email": "Prueba@email.com",
    "contra": "123"
}

###
GET http://localhost:9000/api/users HTTP/1.1

###
GET http://localhost:9000/api/users/Hola HTTP/1.1

###
PUT http://localhost:9000/api/users/65e3dc0632ee94e1b8a8a8ec HTTP/1.1
Content-Type: application/json

{
    "name": "Prueba2",
    "age": 11,
    "email": "Prueba211@email.com"
}

###
DELETE http://localhost:9000/api/users/65e3dc0632ee94e1b8a8a8ec HTTP/1.1